version: '3'

services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
    networks:
      - amqp-network
      
      
      
networks:
  amqp-network:
    driver: bridge    
    ipam:
      driver: default
